from Deque import Deque

deque = Deque()

print("------------- add_first -------------")
print(f"is_empty: {deque.is_empty()}")
deque.add_first(1)
deque.add_first(2)
deque.add_first(3)
deque.add_first(4)
deque.add_first(5)
deque.print_all()
print(f"is_empty: {deque.is_empty()}")
print("\n")

print("------------- remove_first -------------")
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
deque.remove_first()
deque.print_all()
print(f"is_empty: {deque.is_empty()}")
print("\n")

print("------------- add_last -------------")
deque.add_last(1)
deque.add_last(2)
deque.add_last(3)
deque.add_last(4)
deque.add_last(5)
deque.print_all()
print(f"is_empty: {deque.is_empty()}")
print("\n")

print("------------- remove_last -------------")
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
deque.remove_last()
deque.print_all()
print(f"is_empty: {deque.is_empty()}")
print("\n")